"""Add KB models (Article, Category, Supplier, ArticleView)

Revision ID: 7f4d54faf4d3
Revises: 76740c7ffcad
Create Date: 2025-10-19 14:29:08.945451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f4d54faf4d3'
down_revision = '76740c7ffcad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_article_title'))
        batch_op.create_foreign_key('fk_article_supplier', 'supplier', ['supplier_id'], ['id'])

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))
        batch_op.drop_index(batch_op.f('ix_category_name'))
        batch_op.create_unique_constraint('uq_category_name', ['name'])

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_info', sa.Text(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_supplier_category'))
        batch_op.drop_index(batch_op.f('idx_supplier_name'))
        batch_op.drop_index(batch_op.f('ix_supplier_name'))
        batch_op.create_unique_constraint('uq_supplier_name', ['name'])
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('contact_name')
        batch_op.drop_column('category')
        batch_op.drop_column('description')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('contact_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.TEXT(), nullable=True))
        batch_op.drop_constraint('uq_supplier_name', type_='unique')
        batch_op.create_index(batch_op.f('ix_supplier_name'), ['name'], unique=1)
        batch_op.create_index(batch_op.f('idx_supplier_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('idx_supplier_category'), ['category'], unique=False)
        batch_op.alter_column('website',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('contact_info')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('uq_category_name', type_='unique')
        batch_op.create_index(batch_op.f('ix_category_name'), ['name'], unique=1)
        batch_op.drop_column('color')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint('fk_article_supplier', type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_article_title'), ['title'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('supplier_id')

    # ### end Alembic commands ###
